spring.application.name=Fsad-s29-Project
server.port=${PORT:8080}

#connection properties

# PostgreSQL Connection (Render)

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:postgresql://fsad_user:CN9FzuJuFbV2R1zwEbyMT7R7tTg2txI0@dpg-d7qrmp9kh4rs73ef0pn0-a/fsad_lf1k
#spring.datasource.username=fsad_user
#spring.datasource.password=CN9FzuJuFbV2R1zwEbyMT7R7tTg2txI0

#hibernate properties

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring mail properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kammelavishalsuryakoti@gmail.com
spring.mail.password=amkv miwg zazz kbdu
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
